- import_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- import_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"

- import_tasks: "Linux.yml"
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
