- name: (REHL/CentOS) Check if zabbix-release package is present
  yum:
    list: zabbix-release
  register: is_present

- name: debug
  debug:
    msg: "{{ is_present }}"


- name: (REHL/CentOS) Download zabbix-release package
  get_url:
    url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ zabbix_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm" # noqa 204
    dest: /tmp/zabbix-release.rpm
  when: is_present.results | length == 0

- name: (REHL/CentOS) Install zabbix-release package
  yum:
    name: /tmp/zabbix-release.rpm
    state: present
  when: is_present.results | length == 0

- name: (REHL/CentOS) Remove downloaded package
  file:
    path: /tmp/zabbix-release.rpm
    state: absent
  when: is_present.results | length == 0

- name: (REHL/CentOS) Yum update cache
  yum:
    update_cache: yes
  when: is_present.results | length == 0
